### ISSUE TITLE
Add custom request states

### ISSUE THREAD

**Issue by garethrees** [mysociety/derechoapreguntar-theme#117]
```diff
Esta solicitud está todavía en proceso:
+ Me han pedido que aclare mi solicitud
+ Estoy preguntando por mi solicitud de información
```

```diff
Otros:
+ Esta solicitud requiere la intervención de un administrador  
+ Me gustaría retirar esta solicitud  
```

**Comment by JenMysoc** [comment]
Translations as follows:

This request is still in progress:
+ They have asked me to clarify my request
+ I am asking about my information request

Others:
+ This request requires the intervention of an admin
+ I would like to rescind this request

**Comment by garethrees** [comment]
> They have asked me to clarify my request

This already exists http://alaveteli.org/docs/customising/states/#waiting_clarification

> This request requires the intervention of an admin

This already exists http://alaveteli.org/docs/customising/states/#requires_admin

> I would like to rescind this request

This already exists

**Comment by garethrees** [comment]
> I am asking about my information request

I don't really get what this state is meant to show – it just sounds like its "in progress" at this point.

**Comment by JenMysoc** [comment]
I am not sure either but that's the translation :/

**Comment by garethrees** [comment]
![screen shot 2015-04-02 at 17 02 02](https://cloud.githubusercontent.com/assets/282788/6967849/15224ca8-d95a-11e4-8659-a4899706906f.png)

**Comment by garethrees** [comment]
```diff
# This request requires the intervention of an admin
+ Esta solicitud requiere la intervención de un administrador

# I would like to rescind this request
+ Me gustaría retirar esta solicitud 
```

These both already exist:

![screen shot 2015-04-02 at 17 13 33](https://cloud.githubusercontent.com/assets/282788/6968102/fa0b0e1c-d95b-11e4-961e-0357f8c138da.png)

![screen shot 2015-04-02 at 17 17 14](https://cloud.githubusercontent.com/assets/282788/6968136/28107b30-d95c-11e4-8713-930cc9a75dde.png)

**Comment by garethrees** [comment]
We'll look at improving the items in the "others" section in https://github.com/mysociety/alaveteli/issues/2282

**Comment by garethrees** [comment]
Fixed as of https://groups.google.com/a/mysociety.org/d/msg/international/LELrW7HCezI/6WMBDXPJ3LQJ
