### ISSUE TITLE
Add in logo for new donor

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/derechoapreguntar-theme#126]
![logo experimentos civicos-02](https://cloud.githubusercontent.com/assets/4170351/7275873/3367dd96-e8fe-11e4-937d-66731c4f1caf.jpg)

This needs to be added to the website before launch!

**Comment by garethrees** [comment]
Where should it link to?

**Comment by JenMysoc** [comment]
No URL needed at the moment.
