### ISSUE TITLE
Change the text on the sent message

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/derechoapreguntar-theme#127]
Please change the text on the sent request message from

Su acceso a la informacion ha sido enviado

to

Su solicitud de acceso a la información ha sido enviada

**Comment by garethrees** [comment]
The translation string is `"Your {{law_used_full}} request has been sent"`

![screen shot 2015-04-24 at 16 31 46](https://cloud.githubusercontent.com/assets/282788/7322411/ccdfbd48-ea9f-11e4-9403-6922304082b6.png)

The translation string that ends up in `{{law_used_full}}` is `"Freedom of Information"`:

![screen shot 2015-04-24 at 16 32 20](https://cloud.githubusercontent.com/assets/282788/7322459/04631378-eaa0-11e4-8576-414da6eff15e.png)

Changing `acceso a la información` to `solicitud de acceso a la información` would change it everywhere on the site where the `"Freedom of Information"` translation string is used on its own.

**Comment by garethrees** [comment]
@JenMysoc can you check with Javier that this won't screw up any other bits of the site?

**Comment by JenMysoc** [comment]
So the idea I think is that you don't change the acceso a la informacion bit but put the solicitud in between the Su and {{codey stuff}}

**Comment by garethrees** [comment]
Actually yes, think we can just change it to:

```
Su solicitud de {{law_used_full}} ha sido enviada
```

I'll do that – was thinking they'd need to change tho other translation string

**Comment by JenMysoc** [comment]
\o/ awesome!

**Comment by garethrees** [comment]
done
