### ISSUE TITLE
Delete all remaining test data from DerechoAPreguntar

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/derechoapreguntar-theme#129]
everything from here: https://derechoapreguntar.org/list/all

And on Maria Lilly's list

**Comment by garethrees** [comment]
> Dear Garteth need to delete this authority, but will not let me .. you can help me.
>
> ![image 8](https://cloud.githubusercontent.com/assets/282788/7367455/781891ea-ed97-11e4-95a2-a129e8f073ac.png)

**Comment by garethrees** [comment]
Only requests remaining are from the last three days, so I'll leave those for @jbaezni to manage.
