### ISSUE TITLE
Change password on DerechoAPreguntar website at 1900GMT Weds 29 April

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/derechoapreguntar-theme#131]
@jbaezni has asked for the password for derechoapreguntar to be changed at 12 noon Nicaraguan time / 7pm GMT on Wednesday 29th April. This is when their workshop with the officials ends.

Original message:

Como tu sabrás el miércoles tendremos un taller con funcionarios del gobierno y algunos invitados, ellos harán pruebas de la plataforma y obviamente tendrán que entrar con la clave.
Por lo que te pediría sí es posible generar otra nueva clave a partir de las doce del día hora de Nicaragua el día Miércoles.  Para evitar cualquier manipulación antes del lanzamiento oficial donde quedaría libre para ser utilizada la página Web.  Una ves generada una nueva clave no las envías para poder entrar de nuevo. 

Translation:

As you know, Wednesday we have a workshop with government functionaries and other guests, who will test the platform and must enter using the password. What I would like to ask is, is it possible to generate a new password from 12 noon on Wednesday, Nicaraguan time. This is to ensure there will be no changes made before the official launch when we will let the webpage be freely used. Please send us the new password when it's been generated so we can access the site.

**Comment by garethrees** [comment]
Done
