### ISSUE TITLE
Change Violeta de Chamorro logo

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/derechoapreguntar-theme#137]
Please change the violeta de chamorro logo to this
![logo fvbch](https://cloud.githubusercontent.com/assets/4170351/7649893/279d3040-fae9-11e4-954d-a6f40a50d99a.JPG)

**Comment by garethrees** [comment]
Fixed by https://github.com/mysociety/derechoapreguntar-theme/commit/044f40efcf4281b4d87312f061758ae3ab3aaaad
