### ISSUE TITLE
Add video tutorial to homepage

### ISSUE THREAD

**Issue by garethrees** [mysociety/derechoapreguntar-theme#150]
https://youtu.be/bjC6wlFcuLo

> They want a link to it (link text: 'Cómo hacer uso de Derecho a Preguntar') with a little icon of a camera, to go at the top of the homepage under 'Iniciar sesión o registro'.

> I think I need to check with him that he only wants a link and a camera icon, not the full video embedded into the page, like on AsktheEU for example.

**Comment by garethrees** [comment]
I think they should embed it on the homepage

**Comment by jbaezni** [comment]
The video must be encrusted

Saludos 
Javier Báez 

https://4life.com/jbaez

http://jbaezni.webnode.es/

Enviado desde mi iPhone

**Comment by garethrees** [comment]
https://groups.google.com/a/mysociety.org/d/msg/alaveteli/AwexeM99pRU/IirWKighCgAJ
